### PR TITLE
feat(common): add redis cluster support

### PR DESCRIPTION
**Pull request by cloorc**
This PR will close request #507 .

Please have a look. thanks!

### CODE REVIEW

**Comment by cloorc** [comment]
@yedf2 Hi, would you please help to review this PR? Thanks a lot!

**Comment by yedf2** [comment]
Can you make a small typo PR? I'll merge it and you'll be granted privileges to run CI.

After that, you can fix the CI error for this PR.

**Comment by cloorc** [comment]
> Can you make a small typo PR? I'll merge it and you'll be granted privileges to run CI.
> 
> After that, you can fix the CI error for this PR.

Yeah. This PR will only make it possible to connect to redis cluster.

But the old `github.com/go-redis/redis/v8` has issue when ping the cluster. So I had to upgrade it to `github.com/redis/go-redis/v9`.

**Comment by cloorc** [comment]
> Can you make a small typo PR? I'll merge it and you'll be granted privileges to run CI.
> 
> After that, you can fix the CI error for this PR.

I've submitted a new typo PR: #509 , please have a look.

**Comment by cloorc** [comment]
@yedf2 Sorry, it seems unable to restart failed action `Tests/CI(pull_request)` https://github.com/dtm-labs/dtm/actions/runs/9311309876/job/25630279151?pr=508 . It seems like failed because of upload result.

**Comment by cloorc** [comment]
> @yedf2 Sorry, it seems unable to restart failed action `Tests/CI(pull_request)` https://github.com/dtm-labs/dtm/actions/runs/9311309876/job/25630279151?pr=508 . It seems like failed because of unable to upload result.

It seems like `secret.CODECOV_TOKEN` can't be read in my PR.

**Pull request merged**
