### PR TITLE
support helm charts install

### PR DESCRIPTION
**Pull request by xyctruth**

### CODE REVIEW

**Review by yedf2 — APPROVED** [review]

**Comment by yedf2** [comment]
@xyctruth can you help to add helm charts document to dtm.pub?

**Comment by xyctruth** [comment]
> @xyctruth can you help to add helm charts document to dtm.pub?

of course, I introduced some parameters that users may need to change in charts/README.md, and I will improve it later. then put it in dtm.pub

**Comment by xyctruth** [comment]
> @xyctruth can you help to add helm charts document to dtm.pub?

是不是把 charts 的文档添加到  `dtm.pub/docs/deploy/deploy.md` 最后？

**Comment by yedf2** [comment]
@xyctruth 是的，加到那里就OK了，非常感谢！

**Pull request merged**
